name: Smack CI

env:
  GRADLE_VERSION: 6.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Smack

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8, 11 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      #Caches
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-java${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java${{ matrix.java }}-maven-
            ${{ runner.os }}-
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      #Pre-reqs
      - name: Grab gradle wrapper
        run: |
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip
          unzip gradle-${GRADLE_VERSION}-all.zip
          echo "PATH_TO_GRADLE=./gradle-${GRADLE_VERSION}/bin/gradle" >> $GITHUB_ENV
      - name: Install GraphViz
        run: sudo apt update && sudo apt install graphviz

      #Building
      - name: Build Smack
        run: ${PATH_TO_GRADLE} assemble --stacktrace

      #Testing
      - name: Gradle Check
        run: ${PATH_TO_GRADLE} check --stacktrace

      #Publish
      - name: Gradle publish
        run: ${PATH_TO_GRADLE} publishToMavenLocal --stacktrace

      #Javadoc
      - name: Javadoc
        if: ${{ matrix.java == 11 }}
        run: ${PATH_TO_GRADLE} javadocAll --stacktrace

      #Test Coverage Report
      - name: Jacoco Test Coverage
        if: ${{ matrix.java == 1.8 }}
        run: ${PATH_TO_GRADLE} jacocoRootReport coveralls

      #Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: smack-java-${{ matrix.java }}
          path: |
            smack-*/build/libs/*.jar
            !**/*-test-fixtures.jar
            !**/*-tests.jar